### ISSUE TITLE
Can't verify on Windows with space in pathname

### ISSUE THREAD

**Issue by bwhite-mdsol** [yaauie/cliver#14]
Using Go, installed at C:\Program Files (x86)\Go Agent..., when I put the binary for PhantomJS in the working folder (C:\Program Files (x86)\Go Agent\pipelines\my_project...) clover can not properly deduce the version.

Escaping the spaces on the path doesn't help.  When I quote the executable_path then I wind up with an EACCES error.  I've been unable to patch the issue or I'd simply post a PR. 

Original error:

Could not find an executable at given path 'C:\Program Files (x86)\Go Agent\pipelines\Local_Scenarios\features\support\phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues). (Cliver::Dependency::NotFound)

Quoting executable_path:

``` ruby
def detect_version(executable_path)
      executable_path = "#\"{executable_path}\"" unless executable_path.index(" ").nil?
          ...
end
```

error: Permission denied - \"C:/Program\ Files\ (x86)/Go\ Agent/pipelines/Local_Scenarios/features/support/phantomjs.EXE\" --version (Errno::EACCES)

**Comment by yaauie** [comment]
Hello, Bob, and thanks for reaching out.

Can I get a few things from you so I can dig in deeper? I'm not on a Windows-based host, but I should be able to debug directly or spin up a VM if it comes to it.
1. your `PATHEXT` environment variable
2. your `PATH` environment variable
3. the full path to your phantomjs executable
4. that phantomjs executable's `--version` output

If you don't feel comfortable sharing all of that in public, I feel free to send to ryan@yaauie.com; my PGP keys and verification can be found at https://keybase.io/yaauie

**Comment by bwhite-mdsol** [comment]
Path=C:\Ruby193\bin;C:\sysinternals\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Java\jre7\bin;C:\Program Files\TortoiseGit\bin;c:\opscode\chef\bin;c:\opscode\chef\embedded\bin;C:\Program Files\7-Zip;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW

Also, in env.rb:

``` ruby
ENV['PATH'] = "features\\support;#{ENV['PATH']}" if ENV['PATH'].index("features\\support").nil?
```

Full path is: C:\Program Files (x86)\Go Agent\pipelines\Local_Scenarios\features\support\phantomjs.EXE

Version output is:  1.9.7

```
C:\Program Files (x86)\Go Agent\pipelines>"C:\Program Files (x86)\Go Agent\pipel
ines\Local_Scenarios\features\support\phantomjs.EXE" --version
1.9.7
```

(The path is quite a mess I know, but I am trying to help a team clean up their CI environment.)

**Comment by yaauie** [comment]
I think that Cliver may be failing to support that relative path; can you try giving it an absolute path instead? `File::absolute_path` should be able to help:

``` ruby
ENV['PATH'] = "#{File.absolute_path('features\\support')};#{ENV['PATH']}" if ENV['PATH'].index("features\\support").nil?
```

I have verified that Windows' `where` command can identify an executable on a relative component of the `PATH` environment variable, but an initial glance at my tests shows that Cliver doesn't go out of its way to support them. I'll dig in deeper when I get a chance tomorrow.

**Comment by bwhite-mdsol** [comment]
same error:

```
Could not find an executable at given path 'C:\Program Files (x86)\Go Agent\pipelines\Local_Scenarios\features\support\phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues). (Cliver::Dependency::NotFound)
```

**Comment by bwhite-mdsol** [comment]
Localized test moving phantomjs.exe to folder "features/support/test bin":

``` ruby
ENV['PATH'] = "#{File.join('features','support','test bin')};#{ENV['PATH']}" if ENV['PATH'].index("test bin").nil?
```

Produces same error as on Go Agent:

```
Could not find an executable at given path 'C:/.../features/support/test bin/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues). (Cliver::Dependency::NotFound)
```

**Comment by bwhite-mdsol** [comment]
A little more information--even when I convert the path to 8.3 format, eliminating the spaces, I get the same failure.  e.g.  'C:/.../features/support/TESTBI~1/phantomjs.EXE', but in the command window I can execute the exe found at the path in the error message using the full path as shown.

**Comment by yaauie** [comment]
Are you truncating part of the path (replacing it with `...`), or is that the literal output?

**Comment by bwhite-mdsol** [comment]
I truncated that to remove a product name--simple path, no spaces or special characters

**Comment by bwhite-mdsol** [comment]
I do get a valid result when I use the 8.3 path calling the version command with Open3.popen3(...) directly.  Doesn't help solve the issue, but does imply the issue is in Cliver somewhere.

Same error occurs when i remove the path ENV var from the equation using the `phantomjs:` arg to the poltergeist driver create:

``` ruby
  Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(
      app,
      window_size: [1280, 1024],
      phantomjs:   File.join(phantomjs_path,"phantomjs.exe"),
      debug:       true
    )
  end
```

**Comment by yaauie** [comment]
Could you provide actual code examples? I have been unsuccessful in replicating your failure.

Spaces are not at fault, at least not on Windows 7, ruby 1.9.3 installed via the Ruby Installer, and Cliver 0.3.2 as demonstrated by this pry session:

``` ruby
> require 'cliver'; {ruby: RUBY_VERSION, cliver: Cliver::VERSION}
# => {:ruby=>"1.9.3", :cliver=>"0.3.2"}
> Cliver.detect!('phantomjs.exe') # should raise; not on my PATH
# $! Cliver::Dependency::NotFound: Could not find an executable ["phantomjs"] on your path.
> ENV['PATH'] = "test\\another helper;#{ENV['PATH']}" # I have a phantomjs.exe in here
# => "test\\another helper;C:\\Windows\\system32;C:\\Windows;C:\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files (x86)\\Git\\bin;C:\\Ruby193\\bin"
> Cliver.detect!('phantomjs')
# => "C:/Users/yaauie/test/another helper/phantomjs.exe"
```

Similar results occur if I use the posix-style `/` as the file separator, and I have verified that the search is appropriately case-insensitive on Windows. 

If my current directory changes, the relative path no longer matches; perhaps your "Go Agent" is not keeping the current directory constant?:

``` ruby
> Cliver.detect!('phantomjs')
# => "C:/Users/yaauie/test/another helper/phantomjs.exe"
> Dir.chdir('..') { Cliver.detect!('phantomjs') }
# $! Cliver::Dependency::NotFound: Could not find an executable ["phantomjs"] on your path.
> Cliver.detect!('phantomjs')
# => "C:/Users/yaauie/test/another helper/phantomjs.exe"
```

**Comment by bwhite-mdsol** [comment]
Clone this repo and follow instructions in README:  https://github.com/bwhite-mdsol/cliver_test

**Comment by yaauie** [comment]
It turns out shelljoin does not correctly escape _commands_ in Windows, it's odd
but I have pushed a patch that should fix it across the board; I will need to do
additional verification across (jruby + rbx + mri) \* (posix + windows), but this
looks promising:

Simplest repro:

``` ruby
# cliver-open3-current.rb
require 'open3'
require 'shellwords'

begin
  command = ['C:\\Users\\yaauie\\test\\another helper\\phantomjs.exe','--version']
  command = command.shelljoin if command.kind_of?(Array)
  $stderr.puts command.inspect
  o,e = Open3.popen3(command) { |i,o,e| i.close; [o.read.chomp,e.read.chomp] }
  puts o, e
rescue Exception => e
  puts "EXCEPTION: #{e}" 
end
```

```
PS C:\Users\yaauie> ruby .\cliver-open3-current.rb
"C:\\\\Users\\\\yaauie\\\\test\\\\another\\ helper\\\\phantomjs.exe --version"
EXCEPTION: No such file or directory - C:\\Users\\yaauie\\test\\another\ helper\\phantomjs.exe --version
```

Fixed:

``` ruby
# cliver-open3-fixed.rb
require 'open3'
require 'shellwords'

begin
  command = ['C:\\Users\\yaauie\\test\\another helper\\phantomjs.exe','--version']
  command = command.shellsplit unless command.kind_of?(Array)
  $stderr.puts command.inspect
  o,e = Open3.popen3(*command) { |i,o,e| i.close; [o.read.chomp,e.read.chomp] }
  puts o, e
rescue Exception => e
  puts "EXCEPTION: #{e} at #{e.backtrace}" 
end
```

```
PS C:\Users\yaauie> ruby .\cliver-open3-fixed.rb
["C:\\Users\\yaauie\\test\\another helper\\phantomjs.exe", "--version"]
1.9.1
```

Diff:

``` diff
   command = ['C:\\Users\\yaauie\\test\\another helper\\phantomjs.exe','--version']
-  command = command.shelljoin if command.kind_of?(Array)
+  command = command.shellsplit unless command.kind_of?(Array)
   $stderr.puts command.inspect
-  o,e = Open3.popen3(command) { |i,o,e| i.close; [o.read.chomp,e.read.chomp] }
+  o,e = Open3.popen3(*command) { |i,o,e| i.close; [o.read.chomp,e.read.chomp] }
   puts o, e
```

While you're waiting for me to get my end of this resolved (it'll be a week; I'm swamped), feel free to follow this guide to getting cliver out of your way: https://github.com/yaauie/cliver#get-out-of-my-way-cliver

**Comment by bwhite-mdsol** [comment]
Thanks for your prompt attention to this--it was a much quicker response than I expected.

**Comment by bwhite-mdsol** [comment]
I can also simply use:

```
  gem 'cliver', :git => 'git://github.com/yaauie/cliver', :ref => '5617ce'
```

in my Gemfile for now.  Thanks, again.

**Comment by DarynHolmes** [comment]
Hi, has his been fixed?

**Comment by yaauie** [comment]
@DarynHolmes I have a WIP on the branch `windows-paths-vs-shellescape`, but it fell off my radar before I had time to fully test it :frowning:

If it's blocking you, let me know and I'll see what I can do. If the above-mentioned branch works for you, that'd be useful information :smile:
