### ISSUE TITLE
Symlink detected as a exec

### ISSUE THREAD

**Issue by paulRbr** [yaauie/cliver#15]
With the following setup:

``` bash
> ls -la /opt/hello/bin
total 0
drwxr-xr-x  2 root  root   68 Aug 29 10:16 ./
drwxr-xr-x  4 root  root  136 Aug 29 10:16 ../
-rwxr-xr-x  1 root  root    0 Aug 29 10:17 hello
```

and

``` bash
lrwxrwxrwx 1 root root 28 Apr 16  2013 /usr/local/bin/hello -> /opt/hello
```

Cliver detects the symlink `/usr/local/bin/hello` as my `hello` exectuable

**EDIT:** the relevant part of my `$PATH` is `/usr/local/bin/hello/bin:/usr/local/bin`

**Comment by yaauie** [comment]
Could you also provide your `$PATH` (at least the relevant bits), and the ruby code to call Cliver?

**Comment by yaauie** [comment]
I think Cliver is seeing the execute bit set on the symlink (via `File::executable?`), and not doing anything special to resolve the symlink to see if the result is an executable file. I should be able to have a solution for you this weekend, or will gladly accept a pull-request.

**Comment by paulRbr** [comment]
I thought that Cliver would see the execute bit of the symlink too. I'll take a look now if I can create a PR

**Comment by yaauie** [comment]
Likely just below [here](https://github.com/yaauie/cliver/blob/develop/lib/cliver/dependency.rb#L212) we could add something to bail if it's a symlink that doesn't point to an executable file.

**Comment by paulRbr** [comment]
follow up in https://github.com/yaauie/cliver/pull/16
