### ISSUE TITLE
Ignore STDERR on version detection

### ISSUE THREAD

**Issue by moser** [yaauie/cliver#4]
In
https://github.com/yaauie/cliver/blob/develop/lib/cliver/detector.rb#L89
STDERR is redirected to STDOUT and also used for the version detection. This causes problems for me.

Some gem tries to find out the version of phantomjs. It's version output looks like this:

```
$ phantomjs --version
STDERR: Fontconfig error: "local.conf", line 18: invalid attribute 'target'
STDOUT: 1.8.1
```

Cliver reports that phantomjs version 18 is installed.

Two possible solutions:
- Ignore STDERR
- Evaluate the two output streams separately and prefer the result from STDOUT

If you tell me which of the solutions you favor, I'll provide you with a pull request for it.

**Comment by yaauie** [comment]
Let's read both, but prefer stdout. A small word of caution: popen3 (and friends) is not particularly well-supported on Jruby, so feel free to submit the P/R before it's entirely perfect to kick off a travis build.

I'm interested to see what approach you take. :+1:

**Comment by yaauie** [comment]
Closing, since #5 has been merged. Thank you!
