### ISSUE TITLE
cliver 0.3 broke parser

### ISSUE THREAD

**Issue by whitequark** [yaauie/cliver#8]
cliver 0.3 cannot detect the ragel version for some reason: https://travis-ci.org/whitequark/parser/jobs/12174556

**Comment by yaauie** [comment]
I'll get on it & solve it today.

**Comment by yaauie** [comment]
@whitequark: I have found the issue and will be pushing out a 3.1 in about an hour.

**Comment by yaauie** [comment]
@whitequark thank you for the report. The issue appears to be fixed in 0.3.1, and I have yanked 0.3.0 from the rubygems index.

**Comment by whitequark** [comment]
Nice, thanks. I think you're only supposed to yank insecure code or similar stuff, since if it _did_ work for someone and they had a 'cliver', '=0.3.0' restriction, you've just broke it. It's unlikely though.

**Comment by yaauie** [comment]
@whitequark 0.3.0 added a new feature but in the process broke the _default_ use-case, which is pretty terrible. Since this lib is still 0.x, I think the better experience is to only leave versions that actually work =/
